# Generated by Django 4.0 on 2021-12-08 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_remove_post_ytvideo_post_slug_alter_post_titulo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='feito',
            field=models.BooleanField(default=False),
        ),
    ]
