# Generated by Django 4.0 on 2021-12-09 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_post_feito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='feito',
        ),
    ]
